create table public.nonce (
  id bigint generated by default as identity not null,
  license_uuid uuid not null,
  nonce varchar not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nonce_pkey primary key (id),
  constraint nonce_nonce_key unique (nonce),
  constraint nonce_license_uuid_fkey foreign key (license_uuid) references public.license (uuid) on delete cascade
);

create index nonce_license_uuid_idx on public.nonce (license_uuid);

alter table public.nonce enable row level security;

grant all on table public.nonce to anon, authenticated, service_role;
grant all on sequence public.nonce_id_seq to anon, authenticated, service_role;
