create table public.subscription (
  id bigint generated by default as identity not null,
  email varchar not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subscription_pkey primary key (id),
  constraint subscription_email_key unique (email)
);

alter table public.subscription enable row level security;

grant all on table public.subscription to anon, authenticated, service_role;
grant all on sequence public.subscription_id_seq to anon, authenticated, service_role;
