create table public.contact_request (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) <= 254),
  company text check (company is null or char_length(company) <= 120),
  budget text check (budget is null or budget in ('under-10k', '10k-25k', '25k-50k', '50k-plus', 'not-sure')),
  message text not null check (char_length(message) between 20 and 4000),
  created_at timestamptz not null default now()
);

alter table public.contact_request enable row level security;

revoke all on table public.contact_request from anon, authenticated;
revoke all on sequence public.contact_request_id_seq from anon, authenticated;
grant all on table public.contact_request to service_role;
grant all on sequence public.contact_request_id_seq to service_role;
